import { Prop } from './types'
const arsenalA = [
 {name:'Sinker',usage:29.1,pa:88,ba:.218,xba:.240,xwoba:.291,whiff:13.7,k:12.8,hard:34.1},
 {name:'Curveball',usage:21.5,pa:61,ba:.196,xba:.218,xwoba:.244,whiff:31.2,k:33.9,hard:29.4},
 {name:'Four Seamer',usage:18.2,pa:55,ba:.245,xba:.263,xwoba:.335,whiff:19.5,k:22.2,hard:42.0},
 {name:'Slider',usage:14.3,pa:41,ba:.207,xba:.246,xwoba:.298,whiff:28.1,k:30.0,hard:31.6},
 {name:'Changeup',usage:9.8,pa:32,ba:.250,xba:.271,xwoba:.321,whiff:22.4,k:18.8,hard:36.0}
]
const rays = [
 {order:1,name:'Y. Díaz',hand:'RHB',pa:254,ba:.286,k:14.2,weakness:'Curveball whiff'},
 {order:2,name:'J. DeLuca',hand:'RHB',pa:183,ba:.241,k:22.4,weakness:'Sinker grounders'},
 {order:3,name:'J. Caminero',hand:'RHB',pa:266,ba:.272,k:24.7,weakness:'Slider chase'},
 {order:4,name:'J. Aranda',hand:'LHB',pa:220,ba:.268,k:23.8,weakness:'Curveball chase'},
 {order:5,name:'B. Lowe',hand:'LHB',pa:246,ba:.236,k:28.9,weakness:'High fastball'},
 {order:6,name:'T. Walls',hand:'SH',pa:160,ba:.215,k:25.1,weakness:'Breaking ball'},
 {order:7,name:'C. Simpson',hand:'LHB',pa:144,ba:.260,k:21.6,weakness:'Offspeed'},
 {order:8,name:'N. Fortes',hand:'RHB',pa:116,ba:.206,k:27.0,weakness:'Slider'},
 {order:9,name:'J. Caballero',hand:'RHB',pa:198,ba:.238,k:23.9,weakness:'Curveball'}
]
const baseStats = [
 {label:'Barrel%', value:'8.9%', avg:'7.6%', good:false}, {label:'HardHit%', value:'38.1%', avg:'37.1%', good:true},
 {label:'K%', value:'24.8%', avg:'22.2%', good:true}, {label:'BB%', value:'7.2%', avg:'8.4%', good:true},
 {label:'xBA', value:'.231', avg:'.243', good:true}, {label:'xSLG', value:'.381', avg:'.408', good:true},
 {label:'WHIP', value:'1.14', good:true}, {label:'ERA', value:'3.42', good:true}
]
export const props: Prop[] = [
 {id:'lugo-k-45',player:'Seth Lugo',team:'KC',opponent:'TB',game:'Royals @ Rays',market:'Pitcher Strikeouts',line:'Over 4.5',odds:'-115',side:'Over',confidence:68,edge:14.2,projection:'5.4 Ks',tag:'Favorable',type:'K',headshot:'SL',summary:'Pitch mix matches Tampa contact holes and the 4.5 line gives room without needing a ceiling start.',risk:'Rays are not a reckless K team so Lugo needs called strikes and breaking-ball whiffs.',recent:[3,6,5,4,5,6,4,2,7,5],recentLine:4.5,statline:baseStats,arsenal:arsenalA,teamSplits:{title:'Tampa Bay vs RHP',items:[{label:'K%',value:'23.7%',good:true},{label:'O-Swing%',value:'31.8%',good:true},{label:'Contact%',value:'76.9%',good:true},{label:'SwStr%',value:'11.2%',good:true},{label:'wRC+',value:'96',good:true},{label:'ISO',value:'.138',good:true}]},lineup:rays,writeup:['Lugo throws a deep arsenal so this is not one pitch carrying the play. Tampa has several bats that chase breaking balls and Lugos curveball/slider combo grades as the cleanest K path.','The 4.5 number matters because he does not need 7+ to pay it off. A normal 90 pitch workload with 22 to 24 batters faced puts 5 strikeouts in range.','Main risk is Tampa staying contact heavy early and forcing Lugo into quick balls in play instead of two strike counts.']},
 {id:'messick-outs-u175',player:'Parker Messick',team:'CLE',opponent:'CWS',game:'Guardians @ White Sox',market:'Pitching Outs',line:'Under 17.5',odds:'-120',side:'Under',confidence:71,edge:15.4,projection:'16.8 outs',tag:'Favorable',type:'Outs',headshot:'PM',summary:'Recent workload lives in the 5 to 6 inning band and 18 outs requires a cleaner leash than he usually gets.',risk:'Weak opponent can create efficient innings and stretch him into the sixth.',recent:[15,17,18,16,17,15,16,18,14,17],recentLine:17.5,statline:[...baseStats,{label:'L5 IP/start',value:'5.3',good:false},{label:'P/IP',value:'16.7',good:false}],arsenal:arsenalA.map(p=>({...p,usage:Math.max(6,p.usage-3)})),teamSplits:{title:'Chicago White Sox vs LHP',items:[{label:'K%',value:'24.9%',good:false},{label:'BB%',value:'7.1%',good:true},{label:'OBP',value:'.296',good:true},{label:'wRC+',value:'84',good:true},{label:'GB%',value:'44.0%',good:false},{label:'Team Total',value:'3.4',good:true}]},lineup:rays.map((b,i)=>({...b,name:['M. Vargas','L. Robert Jr','A. Benintendi','A. Vaughn','E. Sosa','K. Teel','C. Montgomery','B. Baldwin','J. Amaya'][i],hand:i%3===1?'RHB':'LHB',k:20+i})),writeup:['This is a workload under more than a fade of talent. Messick can pitch fine and still land short because 17.5 asks for 18 outs.','The rolling profile points to 5.1 to 5.2 innings more often than a clean full six. That makes the under live even in a competitive start.','The danger is the White Sox failing to extend innings and giving him a cheap pitch count path.']},
 {id:'pca-hrr-15',player:'Pete Crow-Armstrong',team:'CHC',opponent:'NYM',game:'Cubs @ Mets',market:'Hits + Runs + RBIs',line:'Over 1.5',odds:'+105',side:'Over',confidence:64,edge:9.8,projection:'1.9 HRR',tag:'Neutral',type:'HRR',headshot:'PCA',summary:'Volume plus speed gives multiple ways to clear without needing a homer.',risk:'Lower team total or batting fifth can cap plate appearances.',recent:[2,1,3,2,4,1,2,0,3,2],recentLine:1.5,statline:[{label:'AVG',value:'.292',avg:'.248',good:true},{label:'SLG',value:'.521',avg:'.408',good:true},{label:'HardHit%',value:'42.1%',good:true},{label:'K%',value:'19.1%',good:true},{label:'L10 Hit Rate',value:'80%',good:true},{label:'Team R/G',value:'4.7',good:true}],arsenal:arsenalA,lineup:rays,teamSplits:{title:'Cubs vs RHP',items:[{label:'AVG',value:'.255',good:true},{label:'OBP',value:'.329',good:true},{label:'SLG',value:'.421',good:true},{label:'K%',value:'21.0%',good:true},{label:'wRC+',value:'108',good:true},{label:'ISO',value:'.166',good:true}]},writeup:['PCA has paths through hits, runs, and RBI so this is a better volume bet than a pure power bet.','The profile gets stronger if he stays in the top five because he gets RBI chances and enough plate appearances to run into two events.','Risk is mostly context. If Chicago struggles to turn the lineup over, HRR can die even with one hit.']},
 {id:'woo-k-55',player:'Bryan Woo',team:'SEA',opponent:'PIT',game:'Mariners @ Pirates',market:'Pitcher Strikeouts',line:'Over 5.5',odds:'+100',side:'Over',confidence:73,edge:18.1,projection:'6.8 Ks',tag:'Favorable',type:'K',headshot:'BW',summary:'High fastball usage lines up with a Pirates lineup that whiffs above average vs velocity.',risk:'Woo can be efficient with contact and finish with innings but not strikeouts.',recent:[7,6,8,5,7,4,9,6,7,5],recentLine:5.5,statline:[{label:'K%',value:'27.6%',avg:'22.2%',good:true},{label:'BB%',value:'5.4%',avg:'8.4%',good:true},{label:'CSW%',value:'31.8%',good:true},{label:'Whiff%',value:'28.4%',good:true},{label:'Pitches/start',value:'94',good:true},{label:'xBA',value:'.219',good:true}],arsenal:[{name:'Four Seamer',usage:46.2,pa:120,ba:.205,xba:.221,xwoba:.285,whiff:27.8,k:31.2,hard:32.0},{name:'Sinker',usage:20.4,pa:75,ba:.244,xba:.260,xwoba:.315,whiff:12.1,k:14.7,hard:38.4},{name:'Slider',usage:18.0,pa:66,ba:.188,xba:.211,xwoba:.255,whiff:36.4,k:39.1,hard:28.7},{name:'Changeup',usage:9.5,pa:31,ba:.226,xba:.240,xwoba:.310,whiff:25.2,k:22.2,hard:35.0}],teamSplits:{title:'Pittsburgh vs RHP',items:[{label:'K%',value:'25.6%',good:true},{label:'SwStr%',value:'12.4%',good:true},{label:'Contact%',value:'74.2%',good:true},{label:'wRC+',value:'88',good:true},{label:'ISO',value:'.129',good:true},{label:'O-Swing%',value:'32.5%',good:true}]},lineup:rays.map((b,i)=>({...b,name:['O. Cruz','B. Reynolds','K. Hayes','A. McCutchen','J. Bart','N. Gonzales','J. Triolo','H. Davis','I. Kiner-Falefa'][i],k:[31,22,19,24,29,25,27,30,15][i]})),writeup:['Woo is the type of K profile you want because the fastball creates the count and the slider finishes the plate appearance.','Pittsburgh brings enough swing-and-miss to make 5.5 look light if Woo gets his normal pitch count.','The under case is simple: early-count contact. If Pittsburgh puts four-seamers in play before the slider shows up, Ks can stay short.']}
]
export function getProp(id:string){ return props.find(p=>p.id===id) }
export const markets = ['All','K','Outs','Hits','HRR','ER']
