import Link from 'next/link';
import { Header } from '@/components/Header';
import { getProp } from '@/lib/data';
import { StatPill } from '@/components/StatPill';
import { ArsenalTable } from '@/components/ArsenalTable';
import { TeamSplits } from '@/components/TeamSplits';
import { LineupTable } from '@/components/LineupTable';
import { TrendChart } from '@/components/TrendChart';
export default function PropPage({params}:{params:{id:string}}){const p=getProp(params.id);return <><Header/><main className="mx-auto max-w-5xl p-4 pb-24"><Link href="/" className="pill inline-flex">← Back to props</Link><section className="mt-4 rounded-[2rem] bg-gradient-to-br from-emerald-900/50 via-slate-900 to-purple-900/60 p-6 shadow-glow"><div className="text-white/55">{p.game} • {p.hand}</div><h1 className="mt-2 text-4xl font-black">{p.player}</h1><p className="mt-1 text-white/70">{p.team} vs {p.opponent}</p><div className="mt-5 rounded-3xl bg-white/10 p-4"><div className="text-sm text-white/55">{p.type}</div><div className="text-3xl font-black">{p.side} {p.line} <span className="text-edge">{p.odds}</span></div></div></section><section className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-5"><StatPill label="Projection" value={p.projection}/><StatPill label="Confidence" value={`${p.confidence}%`} tone={p.confidence>65?'good':'warn'}/><StatPill label="Edge" value={`${p.edge}%`} tone="good"/><StatPill label="L10 Hit" value={`${p.hitRateL10}%`} tone={p.hitRateL10>55?'good':'bad'}/><StatPill label="Avg" value={p.avg}/></section><section className="mt-4 glass rounded-3xl p-4"><div className={`mb-3 inline-flex rounded-full px-3 py-1 text-xs font-bold ${p.status==='Favorable'?'green':p.status==='Risky'?'red':'yellow'}`}>{p.status}</div><h2 className="text-2xl font-black">Key Analysis</h2><p className="mt-3 text-white/70">{p.summary}</p><ul className="mt-4 space-y-3 text-white/75">{p.keyAnalysis.map((x,i)=><li key={i}>• {x}</li>)}</ul></section><section className="mt-4 grid gap-4 md:grid-cols-2"><div className="glass rounded-3xl p-4"><h2 className="text-xl font-black">Matchup</h2>{p.matchup.map((x,i)=><p key={i} className="mt-3 text-white/70">{x}</p>)}</div><div className="glass rounded-3xl p-4"><h2 className="text-xl font-black">Game Script</h2>{p.gameScript.map((x,i)=><p key={i} className="mt-3 text-white/70">{x}</p>)}<div className="mt-4 rounded-2xl bg-red-500/10 p-3 text-sm text-red-200">Risk: {p.risk}</div></div></section><section className="mt-4"><TrendChart data={p.trends} line={p.line}/></section><section className="mt-4"><ArsenalTable arsenal={p.arsenal}/></section><section className="mt-4"><TeamSplits s={p.teamSplits} opponent={p.opponent}/></section><section className="mt-4"><LineupTable lineup={p.lineup}/></section><section className="mt-4 glass rounded-3xl p-4"><h2 className="text-xl font-black">AI Writeup</h2><p className="mt-3 leading-7 text-white/75">{p.player} {p.side} {p.line} is graded as {p.status.toLowerCase()} because the projection sits at {p.projection} with {p.confidence}% confidence. The model weighs recent trend, opponent profile, pitch mix, lineup contact rates, and expected workload. This is research support only, not a guarantee.</p></section></main></>}
