import Link from 'next/link'
import { notFound } from 'next/navigation'
import { Header } from '@/components/Header'
import { StatPill } from '@/components/StatPill'
import { ArsenalTable } from '@/components/ArsenalTable'
import { TeamSplits } from '@/components/TeamSplits'
import { LineupTable } from '@/components/LineupTable'
import { TrendChart } from '@/components/TrendChart'
import { getProp, props } from '@/lib/data'
export function generateStaticParams(){return props.map(p=>({id:p.id}))}
export default function PropDetail({params}:{params:{id:string}}){const prop=getProp(params.id); if(!prop) return notFound(); return <main><Header/><section className="mx-auto max-w-7xl px-4 py-6"><Link href="/" className="pill inline-block">← Back to props</Link><div className="mt-4 rounded-[2rem] border border-white/10 bg-gradient-to-br from-purple/25 via-card to-green/10 p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><div className="grid h-16 w-16 place-items-center rounded-3xl bg-purple/30 text-xl font-black">{prop.headshot}</div><div><div className="text-sm text-white/45">{prop.game}</div><h1 className="text-4xl font-black">{prop.player}</h1><p className="mt-1 text-white/55">{prop.market} — {prop.line} {prop.odds}</p></div></div><div className="rounded-2xl border border-green/30 bg-green/10 px-4 py-2 text-center text-green"><div className="text-xs uppercase tracking-widest">Confidence</div><div className="text-3xl font-black">{prop.confidence}%</div></div></div></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4"><StatPill label="Projection" value={prop.projection} good/><StatPill label="Edge" value={`${prop.edge}%`} good/><StatPill label="Market" value={prop.type}/><StatPill label="Grade" value={prop.tag} good={prop.tag==='Favorable'}/></div><div className="mt-6 grid gap-4 lg:grid-cols-[1fr_.85fr]"><div className="glass rounded-3xl p-5"><h2 className="text-2xl font-black">Key Analysis</h2><p className="mt-3 text-lg text-white/75">{prop.summary}</p><div className="mt-4 rounded-2xl border border-red/20 bg-red/10 p-4"><div className="text-sm font-black text-red">Biggest Risk</div><p className="mt-1 text-white/65">{prop.risk}</p></div><div className="mt-4 space-y-3">{prop.writeup.map((w,i)=><p key={i} className="rounded-2xl border border-white/10 bg-black/20 p-4 text-white/65">{w}</p>)}</div></div><div className="glass rounded-3xl p-5"><h2 className="text-2xl font-black">Stat Profile</h2><div className="mt-4 grid grid-cols-2 gap-3">{prop.statline.map(s=><StatPill key={s.label} label={s.label} value={s.value} good={s.good}/>)}</div></div></div><div className="mt-6 grid gap-4 lg:grid-cols-2"><TrendChart recent={prop.recent} line={prop.recentLine}/><TeamSplits title={prop.teamSplits.title} items={prop.teamSplits.items}/></div><div className="mt-6 grid gap-4"><ArsenalTable pitches={prop.arsenal}/><LineupTable lineup={prop.lineup}/></div></section></main>}
